### ISSUE TITLE
Cannot rad 

### ISSUE THREAD

**Issue by lr-sanchez** [AzureADQuickStarts/WebApp-OpenIDConnect-NodeJS#28]
Hello,

I was able to run, login at Microsoft portal. During the call / post to /auth/openid/return I get this error

{"name":"AzureAD: OIDC Passport Strategy","hostname":"RSWIFI-CAPTIVEPORTAL","pid":13841,"level":30,"msg":"PEMkey is generated","time":"2020-02-13T01:42:24.206Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"RSWIFI-CAPTIVEPORTAL","pid":13841,"level":30,"msg":"claims are received","time":"2020-02-13T01:42:24.208Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"RSWIFI-CAPTIVEPORTAL","pid":13841,"level":30,"msg":"we are in implicit flow, use the content in id_token as the profile","time":"2020-02-13T01:42:24.208Z","v":0}
::ffff:189.196.44.134 - - [13/Feb/2020:01:42:24 +0000] "POST /auth/openid/return HTTP/1.1" 500 1071 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.50"
TypeError: Cannot read property 'indexOf' of undefined
    at ServerResponse.res.location (/opt/meraki-azure-ad/node_modules/express/lib/response.js:711:13)
    at ServerResponse.res.redirect (/opt/meraki-azure-ad/node_modules/express/lib/response.js:764:8)
    at /opt/meraki-azure-ad/app.js:269:9
    at callbacks (/opt/meraki-azure-ad/node_modules/express/lib/router/index.js:164:37)
    at complete (/opt/meraki-azure-ad/node_modules/passport/lib/middleware/authenticate.js:268:13)
    at /opt/meraki-azure-ad/node_modules/passport/lib/middleware/authenticate.js:275:15
    at pass (/opt/meraki-azure-ad/node_modules/passport/lib/authenticator.js:431:14)
    at Authenticator.transformAuthInfo (/opt/meraki-azure-ad/node_modules/passport/lib/authenticator.js:453:5)
    at /opt/meraki-azure-ad/node_modules/passport/lib/middleware/authenticate.js:272:22
    at /opt/meraki-azure-ad/node_modules/passport/lib/http/request.js:52:7

Any ideas ?

Thank you

Leandro

**Comment by derisen** [comment]
Closing this as we are archiving this repo. Please refer to https://github.com/Azure-Samples/ms-identity-node instead
